channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - biopython
  - click
  - httmock
  - ipykernel
  - joblib
  - networkx
  - notebook
  - numpy
  - pandas
  - pip
  - pyarrow
  - seaborn
  - sourmash
  - tqdm
  - pip:
    - khmer


