channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - click
  - httmock
  - ipykernel
  - joblib
  - networkx
  - notebook
  - numpy
  - pandas
  - pytest
  - pytest-cov
  - pip
  - pyarrow
  - scikit-learn
  - s3fs
  - seaborn
  - sourmash
  - tqdm
  - pip:
    - khmer


