channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - biopython
  - pytest
  - coverage
  - click
  - ipykernel
  - notebook
  - joblib
  - tqdm
  - numpy
  - sourmash
  - khmer
  - httmock
  - pandas
  - pyarrow
  - pip
  - pip:
    - khmer


