name: Pytest
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        python-version: ['3.6', '3.7']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies with Python ${{ matrix.python_version }}
        shell: bash -l {0}
        run: |
          conda create -n testenv --yes python=${{ matrix.python_version }} pip
          conda activate testenv
          conda install -c bioconda -c conda-forge --yes --file conda_requirements.txt
          pip install -r requirements.txt
          pip install .
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          make coverage

